from datetime import datetime
import logging
import sys
import os
import json

from annotated_types import UpperCase
from generic_scripts_2.utils.postgres_connection import get_connection
from pathlib import Path

# Initialize logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

def read_etl_batch_id(source_name):
    """Read ETL batch ID generated by the batch initialization step."""

    file_path = (
        f"/opt/project/configs/{source_name}_batch_id.txt"
    )

    logger.info(
        "[BATCH] Reading batch metadata | path=%s",
        file_path,
    )

    with open(file_path, "r", encoding="utf-8") as file:
        etl_batch_id = file.readline().strip()

    logger.info(
        "[BATCH] Loaded batch_id=%s",
        etl_batch_id,
    )

    return etl_batch_id


def get_table_count(cursor, schema_name, table_name, etl_batch_id):
    """Fetch count of records for current ETL batch."""

    logger.info(f"Getting table count for {schema_name}.{table_name}")

    query = f"""
        SELECT COUNT(*)
        FROM {schema_name}.{table_name}
        WHERE etl_batch_id = %s
    """

    try:
        cursor.execute(query, (etl_batch_id,))
        table_count = cursor.fetchone()[0]

        logger.info(
            f"Count for {schema_name}.{table_name}: {table_count}"
        )

        return table_count

    except Exception as e:
        logger.error(f"Failed to fetch table count: {e}")
        return None


def get_source_file_count(source_name):
    """Find the latest JSON file for the given source and find the no. of rows"""
    raw_dir = Path(f"/opt/project/data/raw/{source_name}")
    logger.info(f"Checking for raw_data file in {raw_dir}")
    
    files = sorted(raw_dir.glob(f"{source_name}_*.json"))

    if files:
        latest_file = files[-1]
        file_name = latest_file.name
        logger.info(f"Using {file_name}")
        file_path = str(raw_dir)
    else:
        raise FileNotFoundError(f"No {source_name} files found in {raw_dir}")
    
    try:
        os.chdir(file_path)
        with open(file_name, "r", encoding="utf-8") as file:
            data = json.load(file)

        raw_count = len(data)

        logger.info(f"Number of records: {raw_count}")

    except Exception as e:
        logger.error(f"Couldn't read the file: {e}")
    
    return raw_count

def insert_audit_data(cursor,conn,raw_count,table_count,etl_batch_id,source_system,table_name,phase_name="landing"):
    """
    Update audit.batch_log after Landing ANR.
    """

    logger.info(
        "[ANR] Updating batch audit | batch_id=%s | table=%s",
        etl_batch_id,
        table_name,
    )

    if raw_count == table_count:
        batch_status = "C"
        record_count_failed = 0
        error_message = (
            f"ANR validation passed: raw_count={raw_count}, "
            f"landing_count={table_count}"
        )
    else:
        batch_status = "E"
        record_count_failed = abs(raw_count - table_count)
        error_message = (
            f"ANR validation failed: raw_count={raw_count}, "
            f"landing_count={table_count}"
        )

    query = """
        UPDATE audit.batch_log
        SET
            batch_status = %s,
            record_count_processed = %s,
            record_count_failed = %s,
            error_message = %s,
            updated_at = CURRENT_TIMESTAMP
        WHERE etl_batch_id = %s
          AND phase_name = %s
          AND source_system = %s
          AND table_name = %s
    """

    try:

        cursor.execute(
            query,
            (
                batch_status,
                table_count,
                record_count_failed,
                error_message,
                etl_batch_id,
                phase_name,
                source_system,
                table_name
            )
        )

        conn.commit()

        logger.info(
            "[ANR] %s validation completed successfully.",
            table_name
        )

        return batch_status

    except Exception:

        conn.rollback()

        logger.exception(
            "[ANR] Failed updating audit table for %s",
            table_name
        )

        raise
    

def main():
    """Main entry point for Landing ANR"""

    if len(sys.argv) != 5:
        print(
            "Usage: python landing_anr.py "
            "<source_names> <schema_name> <table_names> <source_system>"
        )
        sys.exit(1)

    source_names = sys.argv[1].split(",")
    schema_name = sys.argv[2]
    table_names = sys.argv[3].split(",")
    source_system = sys.argv[4]

    if len(source_names) != len(table_names):
        logger.error("Number of source files and tables do not match.")
        sys.exit(1)

    etl_batch_id = read_etl_batch_id(source_system)

    conn = None
    cursor = None

    try:
        conn = get_connection()

        if not conn:
            logger.error("Can't connect to Postgres.")
            sys.exit(1)

        cursor = conn.cursor()
        logger.info("Connected successfully to Postgres")

        overall_status = "C"

        for source_name, table_name in zip(source_names, table_names):

            logger.info("=" * 80)
            logger.info(f"Validating {source_name} -> {table_name}")
            logger.info("=" * 80)

            landing_count = get_table_count(
                cursor,
                schema_name,
                table_name,
                etl_batch_id
            )

            raw_count = get_source_file_count(source_name)

            if landing_count is None:
                logger.error(f"No data found in {table_name}")
                overall_status = "E"
                continue

            if raw_count is None:
                logger.error(f"No raw file found for {source_name}")
                overall_status = "E"
                continue

            status = insert_audit_data(
                    cursor,
                    conn,
                    raw_count,
                    landing_count,
                    etl_batch_id,
                    source_system,
                    table_name
            )

            if status == "E":
                overall_status = "E"

        if overall_status == "E":
            logger.error("Landing ANR failed.")
            sys.exit(1)

        logger.info("Landing ANR completed successfully.")

    except Exception as e:
        logger.exception(e)
        sys.exit(1)

    finally:
        if cursor:
            cursor.close()

        if conn:
            conn.close()

        logger.info("Closed Connection to Postgres")

if __name__ == "__main__":
    main()