import logging
import sys

from generic_scripts_2.utils.postgres_connection import get_connection

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    force=True,
)
logger = logging.getLogger(__name__)


def read_etl_batch_id(source_system: str) -> str:
    """Read ETL batch ID generated by the batch initialization step."""
    file_path = f"/opt/project/configs/{source_system}_batch_id.txt"
    logger.info("[BATCH] Reading batch metadata | path=%s", file_path)

    with open(file_path, "r", encoding="utf-8") as file:
        etl_batch_id = file.readline().strip()

    logger.info("[BATCH] Loaded batch_id=%s", etl_batch_id)
    return etl_batch_id


def get_table_count(cursor, schema_name, table_name, etl_batch_id):
    """Fetch count of rows for a specific table and ETL batch."""
    logger.info("Getting table count for %s.%s", schema_name, table_name)
    query = f"""
        SELECT COUNT(*)
        FROM {schema_name}.{table_name}
        WHERE etl_batch_id = %s
    """
    try:
        cursor.execute(query, (etl_batch_id,))
        table_count = cursor.fetchone()[0]
        logger.info("Count for %s.%s: %s", schema_name, table_name, table_count)
        return table_count
    except Exception as e:
        logger.error("Failed to fetch table count for %s.%s: %s", schema_name, table_name, e)
        return None


def insert_audit_data(cursor, conn, landing_count, sanitised_count, etl_batch_id, source_system, table_name, phase_name="sanitised"):
    """Update audit.batch_log after Sanitised ANR."""
    logger.info("[ANR] Updating batch audit | batch_id=%s | table=%s", etl_batch_id, table_name)

    if landing_count == sanitised_count:
        batch_status = "C"
        record_count_failed = 0
        error_message = (
            f"ANR validation passed: landing_count={landing_count}, "
            f"sanitised_count={sanitised_count}"
        )
    else:
        batch_status = "E"
        record_count_failed = abs(landing_count - sanitised_count)
        error_message = (
            f"ANR validation failed: landing_count={landing_count}, "
            f"sanitised_count={sanitised_count}"
        )

    query = """
        UPDATE audit.batch_log
        SET
            batch_status = %s,
            record_count_processed = %s,
            record_count_failed = %s,
            error_message = %s,
            updated_at = CURRENT_TIMESTAMP
        WHERE etl_batch_id = %s
          AND phase_name = %s
          AND source_system = %s
          AND table_name = %s
    """

    try:
        cursor.execute(
            query,
            (
                batch_status,
                sanitised_count,
                record_count_failed,
                error_message,
                etl_batch_id,
                phase_name,
                source_system,
                table_name,
            ),
        )
        conn.commit()
        logger.info("[ANR] %s validation completed successfully.", table_name)
        return batch_status
    except Exception:
        conn.rollback()
        logger.exception("[ANR] Failed updating audit table for %s", table_name)
        raise


def main():
    """Main entry point for sanitised ANR."""
    if len(sys.argv) not in (5, 6):
        print(
            "Usage: python sanitised_anr.py <landing_schema> <landing_table> <sanitised_schema> <sanitised_table> [source_system]"
        )
        print(
            "Or: python sanitised_anr.py <landing_schema> <landing_tables_csv> <sanitised_schema> <sanitised_tables_csv> <source_system>"
        )
        sys.exit(1)

    if len(sys.argv) == 5:
        landing_schema = sys.argv[1]
        landing_tables = [sys.argv[2]]
        sanitised_schema = sys.argv[3]
        sanitised_tables = [sys.argv[4]]
        source_system = "music_orchestrator"
    else:
        landing_schema = sys.argv[1]
        landing_tables = [item.strip() for item in sys.argv[2].split(",") if item.strip()]
        sanitised_schema = sys.argv[3]
        sanitised_tables = [item.strip() for item in sys.argv[4].split(",") if item.strip()]
        source_system = sys.argv[5]

    if len(landing_tables) != len(sanitised_tables):
        logger.error("Number of landing tables and sanitised tables do not match.")
        sys.exit(1)

    etl_batch_id = read_etl_batch_id(source_system)

    conn = None
    cursor = None
    overall_status = "C"

    try:
        conn = get_connection()
        if not conn:
            logger.error("Can't connect to Postgres.")
            sys.exit(1)

        cursor = conn.cursor()
        logger.info("Connected successfully to Postgres")

        for landing_table, sanitised_table in zip(landing_tables, sanitised_tables):
            logger.info("=" * 80)
            logger.info("Validating %s -> %s", landing_table, sanitised_table)
            logger.info("=" * 80)

            landing_count = get_table_count(cursor, landing_schema, landing_table, etl_batch_id)
            sanitised_count = get_table_count(cursor, sanitised_schema, sanitised_table, etl_batch_id)

            if landing_count is None or sanitised_count is None:
                logger.error("No data found for the specified table/schema.")
                overall_status = "E"
                continue

            status = insert_audit_data(
                cursor,
                conn,
                landing_count,
                sanitised_count,
                etl_batch_id,
                source_system,
                sanitised_table,
            )

            if status == "E":
                overall_status = "E"

        if overall_status == "E":
            logger.error("Sanitised ANR failed.")
            sys.exit(1)

        logger.info("Sanitised ANR completed successfully.")

    except Exception as e:
        logger.exception(e)
        sys.exit(1)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        logger.info("Closed Connection to Postgres")


if __name__ == "__main__":
    main()