from datetime import datetime
import logging
import sys
import json
from pathlib import Path
import pytz
from generic_scripts.utils.postgres_connection import get_connection


# Initialize logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def get_table_details(cursor, schema_name, table_name):
    """Fetch column names from the target table."""

    logger.info(
        "[TABLE] Fetching column metadata | schema=%s | table=%s",
        schema_name,
        table_name,
    )

    query = """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = %s
          AND table_name = %s
        ORDER BY ordinal_position
    """

    try:
        cursor.execute(query, (schema_name, table_name))
        columns = [row[0] for row in cursor.fetchall()]

        logger.info(
            "[TABLE] Retrieved %s columns | columns=%s",
            len(columns),
            columns,
        )

        return columns

    except Exception:
        logger.exception(
            "[TABLE] Failed fetching metadata | schema=%s | table=%s",
            schema_name,
            table_name,
        )
        return []


def check_files(source_name):
    """Find the latest JSON file for the given source."""

    raw_dir = Path(f"/opt/project/data/raw/{source_name}")

    logger.info(
        "[FILE] Searching raw files | directory=%s",
        raw_dir,
    )

    files = sorted(raw_dir.glob(f"{source_name}_*.json"))

    if not files:
        raise FileNotFoundError(
            f"No {source_name} files found in {raw_dir}"
        )

    latest_file = files[-1]

    logger.info(
        "[FILE] Selected latest file | file=%s",
        latest_file.name,
    )

    return str(latest_file)


def read_etl_batch_id(source_name):
    """Read ETL batch ID generated by the batch initialization step."""

    file_path = (
        f"/opt/project/configs/{source_name}_batch_id.txt"
    )

    logger.info(
        "[BATCH] Reading batch metadata | path=%s",
        file_path,
    )

    with open(file_path, "r", encoding="utf-8") as file:
        etl_batch_id = file.readline().strip()

    logger.info(
        "[BATCH] Loaded batch_id=%s",
        etl_batch_id,
    )

    return etl_batch_id


def insert_data(cursor,conn,columns,source_name,schema_name,table_name,source_system):
    """
    Read JSON data and insert records into the landing table.

    Landing table behavior:
    - Keep duplicate business IDs across batches.
    - Prevent duplicate records within the same batch.
    - Preserve original created_at and etl_batch_id values.
    """

    if not columns:
        logger.warning(
            "[LOAD] No columns retrieved; skipping load"
        )
        return 0

    file_name = check_files(source_name)
    etl_batch_id = read_etl_batch_id(source_system)

    logger.info(
        "[LOAD] Starting landing load | source=%s | table=%s.%s | batch_id=%s",
        source_name,
        schema_name,
        table_name,
        etl_batch_id,
    )

    try:
        with open(file_name, "r", encoding="utf-8") as file:
            data_content = file.read().strip()

        try:
            data_list = json.loads(data_content)

        except json.JSONDecodeError:
            logger.error(
                "[LOAD] Invalid JSON payload | file=%s",
                file_name,
            )
            return 0

        if isinstance(data_list, list):
            data_rows = data_list
        else:
            data_rows = [data_list]

        logger.info(
            "[LOAD] Parsed %s records from source file",
            len(data_rows),
        )

        current_time = datetime.now(pytz.UTC)
        success_count = 0

        # Build INSERT statement
        columns_str = ", ".join(columns)
        placeholders = ", ".join(["%s"] * len(columns))

        cols_lower = [c.lower() for c in columns]

        # Keep duplicates across batches; avoid duplicates within same batch
        if "id" in cols_lower and "etl_batch_id" in cols_lower:
            conflict_clause = "ON CONFLICT (id, etl_batch_id) DO NOTHING"
        else:
            conflict_clause = ""

        insert_sql = f"""
            INSERT INTO {schema_name}.{table_name}
            ({columns_str})
            VALUES ({placeholders})
            {conflict_clause}
        """

        logger.info(
            "[LOAD] Prepared INSERT statement | conflict_strategy=%s",
            conflict_clause or "NONE",
        )

        # Insert rows
        for row in data_rows:
            try:
                values = []

                for col in columns:
                    col_lower = col.lower()

                    # Business key
                    if col_lower in ("id", "artist_id"):
                        val = row.get("id") or row.get("artist_id")

                    # Store full payload
                    elif col_lower == "payload":
                        val = json.dumps(row)

                    # Preserve source created_at if present
                    elif col_lower == "created_at":
                        existing_val = row.get("created_at")

                        if (
                            existing_val is None
                            or existing_val == ""
                            or (
                                isinstance(existing_val, str)
                                and existing_val.lower() in ("none", "null")
                            )
                        ):
                            val = current_time
                        else:
                            val = existing_val

                    # Always update ingestion timestamp
                    elif col_lower == "updated_at":
                        val = current_time

                    # Batch metadata
                    elif col_lower == "etl_batch_id":
                        val = etl_batch_id

                    # Generic column mapping
                    else:
                        val = row.get(col)

                    values.append(val)

                cursor.execute(insert_sql, tuple(values))
                success_count += 1

            except Exception as row_error:
                logger.warning(
                    "[LOAD] Failed processing row | error=%s",
                    row_error,
                )
                continue

        # Commit transaction
        if success_count > 0:
            conn.commit()

            logger.info(
                "[LOAD] Landing load completed | inserted=%s | table=%s.%s | batch_id=%s",
                success_count,
                schema_name,
                table_name,
                etl_batch_id,
            )

        else:
            logger.warning(
                "[LOAD] No rows inserted | table=%s.%s",
                schema_name,
                table_name,
            )

        return success_count

    except Exception:
        conn.rollback()

        logger.exception(
            "[LOAD] Landing load failed | table=%s.%s | batch_id=%s",
            schema_name,
            table_name,
            etl_batch_id,
        )

        return 0


def main():
    """Main entry point for loading landing tables."""

    if len(sys.argv) != 5:
        print(
            "Usage: python load_tables_landing.py <source_name> <schema_name> <table_name> <source_system>"
        )
        sys.exit(1)

    source_name = sys.argv[1]
    schema_name = sys.argv[2]
    table_name = sys.argv[3]
    source_system = sys.argv[4]

    conn = None
    cursor = None

    try:
        conn = get_connection()

        if not conn:
            logger.error("[DB] PostgreSQL connection failed")
            sys.exit(1)

        cursor = conn.cursor()

        logger.info("[DB] PostgreSQL connection established")

        columns = get_table_details(cursor,schema_name,table_name)

        if not columns:
            logger.error("[TABLE] No columns found | schema=%s | table=%s",schema_name,table_name,)
            sys.exit(1)

        rows_affected = insert_data(
            cursor,
            conn,
            columns,
            source_name,
            schema_name,
            table_name,
            source_system
        )

        logger.info("[LOAD] Rows affected=%s",rows_affected,)

    except Exception:
        logger.exception("[FATAL] Landing load process failed")
        sys.exit(1)

    finally:
        if cursor:
            cursor.close()

        if conn:
            conn.close()

        logger.info("[DB] PostgreSQL connection released")


if __name__ == "__main__":
    main()
